# Site settings
title: Unisse C. Chua
email: unisse.chua@dlsu.edu.ph
description: Personal website of Unisse C. Chua
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: sushixuni
github_username:  unissechua

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/
